### ISSUE TITLE
QR code not launched

### ISSUE THREAD

**Issue by SureshVeeraRaghavan** [bibinprathap/whatsapp-chatbot#3]
Hey Bipin, post the deployment , I am unable to see the QR code for scan. Can you guide me on addressing this? Also, suggest me on how to add the chatbot flow inside. Not just a coffee, I shall get you a meal :)

**Comment by bibinprathap** [comment]
resolved

![image](https://github.com/user-attachments/assets/7f8a7370-f605-4edc-ba06-cb143c474dbe)
